name: Frontend CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'    
            - run: npm install
            - run: npm run lint
            - run: npm run build  
            # - name: Deploy to Vercel
            #   run: |
            #     curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}